/*
 * File: app/controller/WebsocketController.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('monitor.controller.WebsocketController', {
    extend: 'Ext.app.Controller',

    onLaunch: function() {
        ws = new WebSocket('ws://10.50.24.156:8000');
        ws.onmessage = function(data){
            console.log(Ext.JSON.decode(data.data));
        };
        ws.onopen = function() {
            ws.send(true);
        };
    }

});
