/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('monitor.view.MainView', {
    extend: 'Ext.container.Viewport',

    id: 'mainView',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'mainPanel',
                    resizable: false,
                    layout: {
                        type: 'border'
                    },
                    collapsed: false,
                    manageHeight: false,
                    title: 'WEBSOCKETS MONITOR',
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            region: 'west',
                            split: true,
                            id: '',
                            itemId: 'userList',
                            width: 150,
                            resizable: false,
                            bodyBorder: false,
                            forceFit: true,
                            store: 'UserStore',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'user',
                                    text: 'User'
                                }
                            ],
                            listeners: {
                                itemclick: {
                                    fn: me.onUserListItemClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            flex: 3,
                            region: 'center',
                            split: true,
                            data: {
                                
                            },
                            itemId: 'detailsPanel',
                            resizable: false,
                            layout: {
                                type: 'fit'
                            },
                            bodyBorder: false,
                            bodyPadding: '10 10 10 10',
                            manageHeight: false,
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: 'My Grid Panel',
                                    store: 'MessageStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'content',
                                            text: 'Messages',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onUserListItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getStore('MessageStore').removeAll();
    }

});