/*
 * File: app/controller/WebsocketController.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('monitor.controller.WebsocketController', {
    extend: 'Ext.app.Controller',

    stores: [
        'UserStore'
    ],

    onLaunch: function() {
        ws = new WebSocket('ws://10.50.24.156:8000');
        var wsconnections = {};
        ws.onmessage = function(data){
            data = Ext.JSON.decode(data.data);
            switch(data.action){
                case 'notification':
                    var userList = Ext.ComponentQuery.query('#userList')[0];
                    var selectedUsers = userList.getSelectionModel().getSelection();
                    if(selectedUsers.length === 1){
                        var user = selectedUsers[0];
                        if(user.data.user === data.user){
                            var userStore = Ext.getStore('MessageStore');
                            userStore.add({'content':Ext.JSON.encode(data)});
                        }
                    }
                    break;
                case 'connection':
                    if(Ext.isEmpty(wsconnections[data.user])){
                        Ext.getStore('UserStore').add({'user': data.user});
                        wsconnections[data.user] = true;
                    }
                    break;
            }
        };
        ws.onopen = function() {

            var message ={
                action: 'monitor'
            };
            ws.send(JSON.stringify(message));
        };
    }

});
